### ISSUE TITLE
Check delay in putting data to DB

### ISSUE THREAD

**Issue by sheldak** [membraneframework/membrane_timescaledb_reporter#12]
While testing [Videoroom](https://github.com/membraneframework/membrane_demo/tree/master/webrtc/videoroom) locally with 3 participants, there is a delay between getting data by `membrane_timescaledb_reporter` and putting them to TimescaleDB. It can be observed by using [Membrane Dashboard](https://github.com/membraneframework/membrane_dashboard/tree/master) (it stops showing new data during live update). It occurs most likely because of a lot of metrics data. Potentially delay can grow with time. We need to find a way to optimise putting data to DB.

**Comment by Qizot** [comment]
Probably fixed by #17. Dashboard however should query timestamp with a certain delay when in live mode. It can't query information till the current timestamp as it may happen that the information is still cached in the reporter and not yet persisted to the database which may cause some anomalies to the charts.
